name=EnviroDIY SC16IS7XX
version=1.0.1
author=Appnostic, Sara Damiano
maintainer=Sara Damiano <sdamiano@stroudcenter.org>
sentence=Arduino Library for SC16IS7XX I2C and SPI UART interfaces
paragraph=Arduino Library for SC16IS750, SC16IS751 and SC16IS752 I2C and SPI UART interfaces
category=Signal Input/Output
url=https://github.com/EnviroDIY/SC16IS7XX
architectures=*
depends=
