name=SC16IS7XX
version=2.0.0
author=TD-er, Appnostic, Sara Damiano
maintainer=Sara Damiano <sdamiano@stroudcenter.org>
sentence=Arduino Library for SC16IS752 and SC16IS762 I2C and SPI UART interfaces.
paragraph=This library supports both the port expander and the UART features of the SC16IS752 and SC16IS762.
category=Signal Input/Output
url=https://github.com/EnviroDIY/SC16IS7XX
architectures=*
depends=Adafruit BusIO
